### ISSUE TITLE
Is this the work you are doing

### ISSUE THREAD

**Issue by Rudeguy1** [kornellewy/convnext_unet#2]
I am very interested in your published work. Do you have any corresponding literature to study？

**Comment by kornellewy** [comment]
I make gans for image inprinting (very specific). About unet u should just google sherch "unet pytorch implementation". Implement linke 3 nets from yt. Then go to convnet repo and copy they code. After that try connect convnet block with u net architecture that u implement. I do that to test if taht unet is better then other models (https://github.com/kornellewy/u_net_models). 
But remember if u do some thask ur proioryity is form hight to low 1. Data to train 2. loss funcion 3. model
U can alsow try implement that gan one by one:
https://github.com/eriklindernoren/PyTorch-GAN
I go form 0 to like 0.5 (hero for some) by chosing very hard task in gan and do it (2 .5 years now). 
For working data pipeline and labeling testing (everytinig) i propose u to use zenml and all integrated liberis. 
Sory for english bro, good luch and have fun. :D
